### PR TITLE
I WAS SENT WRONG ZOOM LINK TO THE INTERVIEW

### PR DESCRIPTION
**Pull request by actionless**
closing this since i finally found a channel to reach out via Client Support 😸

### CODE REVIEW

**Comment by actionless** [comment]
image

**Comment by john-dupuy** [comment]
I'm really sorry about this @actionless - I hope we can chat soon.

**Comment by actionless** [comment]
sorry for trying to reach you everywhere, i was just trying to solve it asap to not re-schedule it to another day

have a nice evening!

**Comment by john-dupuy** [comment]
Ha, good thinking on opening a PR :smile: - wish I had seen it sooner. Again, apologies for the inconvenience and looking forward to our chat.

**Comment by actionless** [comment]
no worries, btw please remove the ticket so it won't hang in history of my public PRs here 😸

**Pull request closed without merging**
